# TODO: Todo2 - Setting pubspec.yaml file and add package for application
name: learn_tdd
description: Learn Online TDD

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.2.0

  # Bloc for state management
  flutter_bloc: ^8.1.1

  # Value equality
  equatable: ^2.0.5

  # Functional programming thingies
  dartz: ^0.10.1

  # Remote API
  data_connection_checker_nulls: ^0.0.2
  http: ^0.13.5

  # Local cache
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Testing App
  mockito: ^5.3.2
  build_runner: ^2.2.1

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700